### ISSUE TITLE
Adding a license?

### ISSUE THREAD

**Issue by madscientist** [jehugaleahsa/primitive#3]
Any interest in adding a license to this repo?  https://github.com/jehugaleahsa/primitive/community

I found this repo by following the link at codereview: content posted there is CC-BY-SA (IIRC) but without a license here this version of the code is essentially proprietary: https://help.github.com/articles/licensing-a-repository/

Cheers!

**Comment by jehugaleahsa** [comment]
Yeah, this was just a quick thought experiment. I typically just give my projects to the public domain: http://unlicense.org

**Comment by madscientist** [comment]
Thought experiment maybe, but at the very least it could save a lot of typing for someone as a starting point!  I have a templated data structure in my project which requires its type to have a well-defined ctor and people are always creating new "wrappers" for POD types; I was hoping to find a generic solution and came across your code in codereview.   Very nice idea.

The Unlicense is a predefined license available via GitHub's licensing facility (link above).  You can just choose it and have it committed directly to your master branch without even cloning... super easy.

Cheers!

**Comment by jehugaleahsa** [comment]
Done.
